In [1]:
import pandas as pd

file = pd.read_csv('orders_export (2).csv')
file

,Name,Email,Financial Status,Paid at,Fulfillment Status,Fulfilled at,Accepts Marketing,Currency,Subtotal,Shipping,...,Tax 2 Name,Tax 2 Value,Tax 3 Name,Tax 3 Value,Tax 4 Name,Tax 4 Value,Tax 5 Name,Tax 5 Value,Phone,Receipt Number
0,#811030,jaredmascola2@gmail.com,paid,2020-07-18 15:02:08 -0400,unfulfilled,NaN,yes,USD,18.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.908800e+10,NaN
1,#811030,jaredmascola2@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.908800e+10,NaN
2,#811032,fayrooz.ae0192@gmail.com,paid,2020-07-18 15:05:23 -0400,unfulfilled,NaN,yes,USD,75.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,#811032,fayrooz.ae0192@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,#811032,fayrooz.ae0192@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,#811079,NaN,paid,2020-07-19 22:59:05 -0400,unfulfilled,NaN,yes,USD,36.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.860751e+10,NaN
59,#811082,h.arabaghian@gmail.com,paid,2020-07-20 00:55:52 -0400,unfulfilled,NaN,yes,USD,18.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,#811089,caberytaylor3@gmail.com,paid,2020-07-20 09:56:29 -0400,unfulfilled,NaN,no,USD,40.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,#811089,caberytaylor3@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,#811090,camibolle@gmail.com,paid,2020-07-20 11:33:48 -0400,unfulfilled,NaN,no,USD,18.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
data = file
data

,Name,Email,Financial Status,Paid at,Fulfillment Status,Fulfilled at,Accepts Marketing,Currency,Subtotal,Shipping,...,Tax 2 Name,Tax 2 Value,Tax 3 Name,Tax 3 Value,Tax 4 Name,Tax 4 Value,Tax 5 Name,Tax 5 Value,Phone,Receipt Number
0,#811030,jaredmascola2@gmail.com,paid,2020-07-18 15:02:08 -0400,unfulfilled,NaN,yes,USD,18.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.908800e+10,NaN
1,#811030,jaredmascola2@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.908800e+10,NaN
2,#811032,fayrooz.ae0192@gmail.com,paid,2020-07-18 15:05:23 -0400,unfulfilled,NaN,yes,USD,75.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,#811032,fayrooz.ae0192@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,#811032,fayrooz.ae0192@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,#811079,NaN,paid,2020-07-19 22:59:05 -0400,unfulfilled,NaN,yes,USD,36.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.860751e+10,NaN
59,#811082,h.arabaghian@gmail.com,paid,2020-07-20 00:55:52 -0400,unfulfilled,NaN,yes,USD,18.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,#811089,caberytaylor3@gmail.com,paid,2020-07-20 09:56:29 -0400,unfulfilled,NaN,no,USD,40.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,#811089,caberytaylor3@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,#811090,camibolle@gmail.com,paid,2020-07-20 11:33:48 -0400,unfulfilled,NaN,no,USD,18.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
data['Lineitem name'].describe

<bound method NDFrame.describe of 0                                              Tip
1            Family Tree T-Shirt - Mustard / Large
2       Desert Nights Long Sleeve - Violet / Small
3          Family Tree Long Sleeve - Blue / Medium
4     Desert Nights Long Sleeve - Mustard / Medium
                          ...
58        Desert Nights T-Shirt - Charcoal / Large
59            Family Tree T-Shirt - Berry / Medium
60                                             Tip
61         Family Tree Hoodie - Deep Olive / Large
62         Family Tree T-Shirt - Sandstone / Small
Name: Lineitem name, Length: 63, dtype: object>

In [7]:
items = {}

for i in data['Lineitem name']:
    if i in items.keys():
        items[i] += 1
    else:
        items[i] = 1
items

{'Desert Nights Hoodie - Deep Olive / Large': 1,
 'Desert Nights Hoodie - Sandstone / Large': 2,
 'Desert Nights Hoodie - Sandstone / Medium': 2,
 'Desert Nights Hoodie - Sandstone / X-Large': 2,
 'Desert Nights Long Sleeve - Blue / Small': 1,
 'Desert Nights Long Sleeve - Mustard / Medium': 1,
 'Desert Nights Long Sleeve - Violet / Small': 1,
 'Desert Nights T-Shirt - Berry / Large': 3,
 'Desert Nights T-Shirt - Berry / Medium': 3,
 'Desert Nights T-Shirt - Berry / Small': 1,
 'Desert Nights T-Shirt - Charcoal / Large': 1,
 'Desert Nights T-Shirt - Charcoal / X-Large': 1,
 'Desert Nights T-Shirt - Light Green / Large': 1,
 'Desert Nights T-Shirt - Light Green / Medium': 1,
 'Desert Nights T-Shirt - Mustard / Medium': 1,
 'Desert Nights T-Shirt - Sandstone / Medium': 2,
 'Family Tree Hoodie - Charcoal / Large': 1,
 'Family Tree Hoodie - Deep Olive / Large': 1,
 'Family Tree Hoodie - Deep Olive / Medium': 2,
 'Family Tree Hoodie - Sandstone / Large': 3,
 'Family Tree Long Sleeve - Blue / Large': 1,
 'Family Tree Long Sleeve - Blue / Medium': 1,
 'Family Tree Long Sleeve - Violet / Large': 1,
 'Family Tree Long Sleeve - Violet / Medium': 1,
 'Family Tree T-Shirt - Berry / Large': 1,
 'Family Tree T-Shirt - Berry / Medium': 3,
 'Family Tree T-Shirt - Berry / Small': 1,
 'Family Tree T-Shirt - Light Green / Medium': 1,
 'Family Tree T-Shirt - Mustard / Large': 2,
 'Family Tree T-Shirt - Mustard / Medium': 3,
 'Family Tree T-Shirt - Sandstone / Small': 1,
 'Tip': 16}

In [8]:
items = data['Lineitem name']
tip = 0
blankOrders = {}
for i in range(len(items)):
    if(data['Lineitem name'][i] == 'Tip'):
        tip += data['Lineitem price'][i]
    else:
        blankRaw = data['Lineitem name'][i].split(' ')
        
        if blankRaw[2] == 'T-Shirt':
            if blankRaw[4] == 'Light':
                shirt = blankRaw[2]
                color = blankRaw[4] + ' ' + blankRaw[5]
                size = blankRaw[7]
            else:
                shirt = blankRaw[2]
                color = blankRaw[4]
                size = blankRaw[6]
        elif blankRaw[2] == 'Hoodie':
            if blankRaw[4] == 'Deep':
                shirt = blankRaw[2]
                color = blankRaw[4] + ' ' + blankRaw[5]
                size = blankRaw[7]
            else:
                shirt = blankRaw[2]
                color = blankRaw[4]
                size = blankRaw[6]
                
        else:
            shirt = blankRaw[2] + " " + blankRaw[3]
            color = blankRaw[5]
            size = blankRaw[7]
            
        key = shirt + ' '+ color + ' '+ size
        
        if key not in blankOrders.keys():
            blankOrders[key]  = 1
        else:
            blankOrders[key] += 1

In [9]:
print(blankOrders)

{'T-Shirt Mustard Large': 2, 'Long Sleeve Violet Small': 1, 'Long Sleeve Blue Medium': 1, 'Long Sleeve Mustard Medium': 1, 'Hoodie Sandstone Large': 5, 'T-Shirt Mustard Medium': 4, 'Hoodie Sandstone X-Large': 2, 'T-Shirt Berry Large': 4, 'Long Sleeve Blue Large': 1, 'T-Shirt Berry Medium': 6, 'Long Sleeve Violet Large': 1, 'Hoodie Charcoal Large': 1, 'Hoodie Deep Olive Medium': 2, 'Long Sleeve Blue Small': 1, 'T-Shirt Berry Small': 2, 'Hoodie Deep Olive Large': 2, 'T-Shirt Light Green Medium': 2, 'T-Shirt Sandstone Medium': 2, 'T-Shirt Light Green Large': 1, 'Long Sleeve Violet Medium': 1, 'Hoodie Sandstone Medium': 2, 'T-Shirt Charcoal X-Large': 1, 'T-Shirt Charcoal Large': 1, 'T-Shirt Sandstone Small': 1}

In [10]:
print(tip)

74.0